### ISSUE TITLE
SNI is not used for usage 3

### ISSUE THREAD

**Issue by tribut** [pieterlexis/swede#20]
When using `-u 3` SNI is not used, even if available. This leads to the wrong certificate being used for verification and generation. There is an explicit check for this in two lines of code:

   https://github.com/pieterlexis/swede/blob/master/swede#L637
   https://github.com/pieterlexis/swede/blob/master/swede#L777

Maybe I simply don't "get" what this is supposed to do, but I guess they should just be removed?

**Comment by pieterlexis** [comment]
it has been a long time since I wrote or looked at this code. I'll see what I can do

**Comment by tribut** [comment]
I've created a PR to remove the check for usage == 3 as suggested and it works for me, but again: I do not understand why this check was ever there so ymmv.

**Comment by pieterlexis** [comment]
I have no clue either, years-ago-me's answer is lost to history :) Thanks!

**Comment by tribut** [comment]
😄
